---
title: "In-class_Ex01"
author: "LIU YAN"
date: "6 May 2023"
date-modified: "`r Sys.Date()`"
execute:
  echo: true
  eval: true
  warning: false
editor: visual
---


```{r}
pacman:: p_load(rstatix, gt, patchwork, tidyverse)

```

```{r}
exam_data <- read_csv("data/Exam_data.csv", show_col_types = FALSE)

```
::: panel-tabset

## The plot

```{r}
#| echo: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,
       aes(sample=ENGLISH))+stat_qq()+stat_qq_line()
```

## The code chunk
```{r}
#| eval: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,
       aes(sample=ENGLISH))+stat_qq()+stat_qq_line()
```
:::

::: {.callout-note}
we can see that the points deviate significantly form the straight diagonal line. this is a clear indication that the set of data is not normally distributed.
:::

::: panel-tabset
## The plot
```{r}
#| echo: false
qq <- ggplot(exam_data,
       aes(sample=ENGLISH))+stat_qq()+stat_qq_line()

sw_t <- exam_data %>%
  shapiro_test(ENGLISH)%>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t,tmp)
table_png <- png::readPNG(tmp,
                        native=TRUE)

qq+table_png
  

```

## The code chunk
```{r}
#| eval: false
qq <- ggplot(exam_data,
       aes(sample=ENGLISH))+stat_qq()+stat_qq_line()

sw_t <- exam_data %>%
  shapiro_test(ENGLISH)%>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t,tmp)
table_png <- png::readPNG(tmp,
                        native=TRUE)

qq+table_png
  

```
:::
