project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    logo: "images/visual-analytics-icon.png"
    pinned: true
    align: left
    max-height: 100px
    left: 
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Exercise 1"
          href: "In-class Exercise/In-class Exercise 1/In-class_Ex01.html"
        - text: "In-class Exercise 3"
          href: "In-class Exercise/In-class Exercise 3/In-class_Ex03.html"
        - text: "In-class Exercise 4"
          href: "In-class Exercise/In-class Exercise 4/In-class_Ex04.html"
        - text: "In-class Exercise 5"
          href: "In-class Exercise/In-class Exercise 5/In-class_Ex05.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Exercise 1"
          href: "Take-home Exercise/Take-home Exercise 1/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home Exercise/Take-home Exercise 2/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home Exercise/Take-home Exercise 3/Take-home_Ex03.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    code-fold: true
    code-summary: "show the code"
    theme: flatly
    css: styles.css
    toc: true
execute: 
  echo: true
  eval: true
  warning: false
editor: visual

