project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    logo: "images/visual-analytics-icon.png"
    pinned: true
    align: left
    max-height: 100px
    left: 
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Exercise 1"
          href: "In-class Exercise/In-class Exercise 1/In-class_Ex01.html"
        - text: "In-class Exercise 3"
          href: "In-class Exercise/In-class Exercise 3/In-class_Ex03.html"
        - text: "In-class Exercise 4"
          href: "In-class Exercise/In-class Exercise 4/In-class_Ex04.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Exercise 1"
          href: "Take-home Exercise/Take-home Exercise 1/Take-home_Ex01.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
execute: 
  echo: true
  eval: true
  warning: false
editor: visual

